services:
    file-reader:
        class:  Commission\FileReader
        arguments: ['@payment-creator']
    payment-creator:
        class:  Commission\PaymentCreator
        arguments: ['%payment-creator.config%']