services:
    file-reader:
        class:  Commission\FileReader
    payment-creator:
        class:  Commission\PaymentCreator
        arguments: ['%payment-creator.config%']
    calculator:
        class:  Commission\Calculator
        arguments:
          - '%calculator.config%'
          - '@payments-cache'
          - '@math'
    payments-cache:
        class:  Commission\Entity\PaymentsCache
        arguments:
          - '@math'
    math:
        class:  Commission\Math