services:
    file-reader:
        class:  Commission\FileReader
    payment-creator:
        class:  Commission\PaymentCreator
        arguments: ['%payment-creator.config%']
    calculator:
        class:  Commission\Calculator
        arguments: ['%calculator.config%']